// ============================================================
// AUTO-GENERATED by app/model/export_cls_tflite.py — 직접 수정하지 마세요.
// 번들에 포함된 온디바이스 '분류' 모델 목록. 선택은 src/ml/modelSelectCls.js.
// ============================================================
export const CLS_MODELS = {
  "effb0_224_0.2": { meta: require("../../assets/models/effb0_224_0.2.json"), model: require("../../assets/models/effb0_224_0.2.tflite") },
  "effb0_512_0.2": { meta: require("../../assets/models/effb0_512_0.2.json"), model: require("../../assets/models/effb0_512_0.2.tflite") },
  "mnv3s_224_0.2": { meta: require("../../assets/models/mnv3s_224_0.2.json"), model: require("../../assets/models/mnv3s_224_0.2.tflite") },
  "mnv4s_224_0.2": { meta: require("../../assets/models/mnv4s_224_0.2.json"), model: require("../../assets/models/mnv4s_224_0.2.tflite") },
  "mnv4s_512_0.2": { meta: require("../../assets/models/mnv4s_512_0.2.json"), model: require("../../assets/models/mnv4s_512_0.2.tflite") },
};
export const CLS_MODEL_KEYS = ["effb0_224_0.2", "effb0_512_0.2", "mnv3s_224_0.2", "mnv4s_224_0.2", "mnv4s_512_0.2"];
export const DEFAULT_CLS_MODEL = "effb0_224_0.2";
