// ============================================================
// AUTO-GENERATED by app/model/export_tflite.py — 직접 수정하지 마세요.
// 번들에 포함된 온디바이스 모델 목록. 사용할 모델 선택은 src/ml/modelSelect.js.
// ============================================================
export const MODELS = {
  "effb0_unetpp_128": { meta: require("../../assets/models/effb0_unetpp_128.json"), model: require("../../assets/models/effb0_unetpp_128.tflite") },
  "effb0_unetpp_192": { meta: require("../../assets/models/effb0_unetpp_192.json"), model: require("../../assets/models/effb0_unetpp_192.tflite") },
  "effb0_unetpp_224": { meta: require("../../assets/models/effb0_unetpp_224.json"), model: require("../../assets/models/effb0_unetpp_224.tflite") },
  "effb0_unetpp_256": { meta: require("../../assets/models/effb0_unetpp_256.json"), model: require("../../assets/models/effb0_unetpp_256.tflite") },
  "effb0_unetpp_320": { meta: require("../../assets/models/effb0_unetpp_320.json"), model: require("../../assets/models/effb0_unetpp_320.tflite") },
  "effb0_unetpp_384": { meta: require("../../assets/models/effb0_unetpp_384.json"), model: require("../../assets/models/effb0_unetpp_384.tflite") },
  "effb0_unetpp_512": { meta: require("../../assets/models/effb0_unetpp_512.json"), model: require("../../assets/models/effb0_unetpp_512.tflite") },
  "hrnet_unet_1024": { meta: require("../../assets/models/hrnet_unet_1024.json"), model: require("../../assets/models/hrnet_unet_1024.tflite") },
  "unext_512": { meta: require("../../assets/models/unext_512.json"), model: require("../../assets/models/unext_512.tflite") },
};
export const MODEL_KEYS = ["effb0_unetpp_128", "effb0_unetpp_192", "effb0_unetpp_224", "effb0_unetpp_256", "effb0_unetpp_320", "effb0_unetpp_384", "effb0_unetpp_512", "hrnet_unet_1024", "unext_512"];
export const DEFAULT_MODEL = "effb0_unetpp_128";
